test/package-lock.json, test/src/mock.js
=> #8 fixing faker

src/App.js, src/components/StatusBadge.js, src/components/TableRow.js, src/pages/TemplateWizard.js, src/pages/TemplatesView.js, test/src/mocks/View.json
=> media wizard page

test/src/mocks/InputModel.json, test/src/mocks/OutputModel.json, test/src/mocks/Template.json, test/src/mocks/TemplateResponse.json
added some models to mock back end for clarity
=> updated model jsons

.circleci/config.yml, package-lock.json, src/components/TemplateDragDrop.js, src/pages/SubmitFile.js, src/pages/TemplateDesigner.js, src/pages/TemplateWizard.js
=> new template form fixes

src/App.js, src/components/AuthButton.js, src/components/NavMenu.js
=> Menu links

src/components/TableRow.js, src/pages/TemplateWizard.js, test/src/mocks/OutputResponse.json
Fixes: #75 
- add name to mock
- display name in output list
- add name to the template wizard form
=> Add "name" field to output

src/components/DragDropBox.js, src/components/TemplateDragDrop.js, src/components/TemplateViewInput.js, src/pages/TemplateDesigner.js, src/utils/templateUtils.js
Fixes: #80 
- also, changed the aspect ratio to a checkmark instead of "leave blank". The width wasn't recalculating when the height changed before
- componentize things
- move some helper functions and consts to a util file
- also, set a default height AND width for templates and views. I was encountering a bunch of bugs otherwise
=> Dragdrop responsive

src/components/NavMenu.js
Overleia <-> Beatcaps dropdown
=> menu titles were backwards

src/pages/TemplateDesigner.js
=> fixed designer bug

src/contexts/GlobalState.js, src/pages/SubmitFile.js, test/src/mock.js
=> added id token to api

.env.template, src/components/NavMenu.js, src/constants.js, src/pages/SubmitFile.js
fixes #74 
* `SHOW_BEATCAPS` env var added
* also, new way to do conditional rendering instead of ternary operator
=> env var trigger beatcaps stuff

src/components/TableRow.js, src/components/TemplateDragDrop.js, src/components/TemplateViewInput.js, src/pages/TemplateDesigner.js, src/utils/templateUtils.js
=> Drag drop bugs

src/components/DragDropBox.js, src/components/TableRow.js, src/pages/TemplateDesigner.js, src/utils/templateUtils.js
=> Fixed a bug which sets max width and height ondrag

src/components/DragDropBox.js, src/components/TemplateDragDrop.js, src/components/TemplateViewInput.js, src/pages/Dashboard.js, src/pages/TemplateDesigner.js, src/pages/TemplatesView.js, src/utils/templateUtils.js
locks sixteen by nine aspect ratio on resize
=> sixteen nine aspect ratio lock

src/pages/Dashboard.js, src/pages/FileView.js, src/pages/SubmitFile.js
=> add outputs download button

src/pages/Dashboard.js, src/pages/FileView.js, src/pages/TemplateDetailsPage.js, src/pages/TemplateEditor.js, src/pages/TemplateWizard.js, src/pages/TemplatesView.js
=> added id token to reqs

package-lock.json, package.json, src/pages/SubmitFile.js
fixes https://github.com/goatandsheep/communote-tasks/issues/554
=> only push data if finished

package-lock.json, package.json, src/pages/SubmitFile.js
gh-557 for the image background feature
=> gh-557 expanding the range of accepted files to include .png and .jpeg and .jpg

src/pages/FileView.js
... but the actual percentage is blank, and  now overleia-server gives a strange error
https://github.com/goatandsheep/communote-tasks/issues/554
=> added "Progress:" to the fileview page

package-lock.json, src/App.js, src/pages/BeatcapsWizard.js, src/pages/SubmitFile.js
=> beatcaps upload page

src/pages/FileView.js, src/pages/SubmitFile.js
* fixes #326
* fixes #320
* Co-authored-by: Kemal Ahmed @goatandsheep
=> Fixed Loading Bar and Submit button displacement
